# Generated by Django 5.1.6 on 2025-02-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Seviye 1'), (2, 'Seviye 2'), (3, 'Seviye 3'), (4, 'Seviye 4'), (5, 'Seviye 5'), (6, 'Seviye 6'), (7, 'Seviye 7'), (8, 'Seviye 8'), (9, 'Seviye 9'), (10, 'Seviye 10'), (11, 'Seviye 11'), (12, 'Seviye 12')], verbose_name='Seviye')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Ödül')),
            ],
        ),
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Yanlış Cevap')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to='quiz.question', verbose_name='İlgili Soru')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Doğru Cevap')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='quiz.question', verbose_name='İlgili Soru')),
            ],
        ),
    ]
