# Generated by Django 5.1.6 on 2025-02-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_game_prize',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
